import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, FileText, Pill, RefreshCw } from "lucide-react";
import api from "../../services/api";

const fmt = v => v ? new Date(v).toLocaleDateString("en-IN", {day:"numeric",month:"short",year:"numeric"}) : "—";
const valueOf = v => v?.type === "blood_pressure" ? `${v.systolic}/${v.diastolic}` : `${v?.value ?? "—"} ${v?.unit || ""}`;
const metricLabel = v => ({heart_rate:"Heart rate",blood_pressure:"Blood pressure",blood_glucose:"Blood glucose",spo2:"Oxygen saturation",temperature:"Temperature",respiratory_rate:"Respiratory rate",weight:"Weight"}[v?.type] || v?.type || "Health reading");

export default function HealthTimeline(){
 const [prescriptions,setPrescriptions]=useState([]),[vitals,setVitals]=useState([]),[records,setRecords]=useState([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState(null);
 async function load(refresh=false){setRefreshinging(refresh);setError("");try{const [p,v,r]=await Promise.all([api.get("/prescriptions"),api.get("/vitals?limit=200"),api.get("/medical-records")]);const ps=p.data?.data||[],vs=v.data?.data||[],rs=r.data?.data||[];setPrescriptions(ps);setVitals(vs);setRecords(rs);setSelected(current=>current?ps.find(x=>x._id===current._id)||ps[0]||null:ps[0]||null);}catch(e){setError(e.response?.data?.message||"Unable to load health comparison.")}finally{setLoading(false);setRefreshing(false)}}
 function setRefreshinging(v){setRefreshing(v)}
 useEffect(()=>{load()},[]);
 const comparison=useMemo(()=>{if(!selected)return null;const start=new Date(selected.prescriptionDate||selected.createdAt);const meds=selected.medicines||[];const ends=meds.map(m=>m.endDate&&new Date(m.endDate)).filter(Boolean);const end=ends.length?new Date(Math.max(...ends.map(d=>d.getTime()))):new Date(start.getTime()+14*86400000);const beforeStart=new Date(start.getTime()-7*86400000);const afterEnd=new Date(end.getTime()+7*86400000);const beforeVitals=vitals.filter(x=>{const d=new Date(x.recordedAt);return d>=beforeStart&&d<start});const afterVitals=vitals.filter(x=>{const d=new Date(x.recordedAt);return d>end&&d<=afterEnd});const beforeRecords=records.filter(x=>{const d=new Date(x.documentDate||x.createdAt);return d>=beforeStart&&d<start});const afterRecords=records.filter(x=>{const d=new Date(x.documentDate||x.createdAt);return d>end&&d<=afterEnd});return {start,end,beforeStart,afterEnd,beforeVitals,afterVitals,beforeRecords,afterRecords};},[selected,vitals,records]);
 const summary=(before,after)=>{const map={};before.forEach(v=>{map[metricLabel(v)] ||= [];map[metricLabel(v)].push(v)});const amap={};after.forEach(v=>{amap[metricLabel(v)] ||= [];amap[metricLabel(v)].push(v)});return Object.keys({...map,...amap}).map(k=>{const b=map[k]?.[map[k].length-1],a=amap[k]?.[amap[k].length-1];return {label:k,before:b?valueOf(b):"No reading",after:a?valueOf(a):"No reading"}})};
 return <div className="timeline-simple-page"><div className="timeline-simple-header"><div><span className="page-eyebrow"><Activity size={13}/> HEALTH PROGRESS</span><h1>Before & After Health</h1><p>Compare your stored health readings and medical records around a prescription period.</p></div><button className="secondary-button" onClick={()=>load(true)} disabled={loading||refreshing}><RefreshCw size={15} className={refreshing?"spin":""}/>{refreshing?"Refreshing":"Refresh"}</button></div>
  {!loading&&prescriptions.length>0&&<section className="timeline-prescription-picker"><div><span>PRESCRIPTION PERIOD</span><h2>Select a prescription</h2></div><select value={selected?._id||""} onChange={e=>setSelected(prescriptions.find(x=>x._id===e.target.value)||null)}>{prescriptions.map(p=><option key={p._id} value={p._id}>{fmt(p.prescriptionDate||p.createdAt)} · {(p.medicines||[]).map(m=>m.name).filter(Boolean).join(", ")||"Prescription"}</option>)}</select></section>}
  {error&&<div className="page-error">{error}</div>}
  {loading?<div className="timeline-empty">Loading your health comparison…</div>:!selected?<div className="timeline-empty"><span><Pill size={20}/></span><strong>No prescription history yet</strong><p>Once a doctor issues a prescription, MediTrack will compare the health information before and after that treatment period.</p></div>:<>
   <section className="timeline-period-card"><div><span>BEFORE</span><strong>{fmt(comparison.beforeStart)} — {fmt(comparison.start)}</strong></div><ArrowRight size={22}/><div><span>AFTER</span><strong>{fmt(comparison.end)} — {fmt(comparison.afterEnd)}</strong></div></section>
   <section className="timeline-compare-card"><div className="timeline-compare-heading"><div><span>HEALTH COMPARISON</span><h2>What changed around the prescription?</h2></div><span className="timeline-medicine-badge"><Pill size={13}/> {(selected.medicines||[]).length} medicine{(selected.medicines||[]).length===1?"":"s"}</span></div>
    <div className="timeline-compare-table"><div className="timeline-table-head"><span>Health measure</span><span>Before</span><span>After</span></div>{summary(comparison.beforeVitals,comparison.afterVitals).length?summary(comparison.beforeVitals,comparison.afterVitals).map(x=><div className="timeline-table-row" key={x.label}><strong>{x.label}</strong><span>{x.before}</span><span>{x.after}</span></div>):<div className="timeline-no-data">No health readings were recorded in the comparison windows.</div>}</div>
   </section>
   <section className="timeline-record-compare"><div className="timeline-record-column"><div className="timeline-column-title"><FileText size={17}/><div><span>BEFORE PRESCRIPTION</span><h3>Medical records</h3></div><strong>{comparison.beforeRecords.length}</strong></div>{comparison.beforeRecords.length?comparison.beforeRecords.map(r=><Record key={r._id} record={r}/>):<p className="timeline-muted">No medical records in the 7 days before treatment.</p>}</div><div className="timeline-record-column"><div className="timeline-column-title"><FileText size={17}/><div><span>AFTER PRESCRIPTION</span><h3>Medical records</h3></div><strong>{comparison.afterRecords.length}</strong></div>{comparison.afterRecords.length?comparison.afterRecords.map(r=><Record key={r._id} record={r}/>):<p className="timeline-muted">No medical records in the 7 days after treatment.</p>}</div></section>
   <div className="timeline-note"><strong>How this works</strong><span>MediTrack compares stored information only. It does not determine whether a medicine caused an improvement or deterioration. Discuss important changes with your doctor.</span></div>
  </>}
 </div>
}
function Record({record}){return <div className="timeline-record-item"><FileText size={16}/><div><strong>{record.title}</strong><span>{record.category?.replaceAll("_"," ")||"Medical record"} · {fmt(record.documentDate||record.createdAt)}</span>{record.doctorName&&<small>Doctor: {record.doctorName}</small>}</div></div>}
