import { useEffect, useState } from "react";
import { Activity, ArrowRight, CalendarDays, ChevronRight, FileHeart, HeartPulse, Pill, Sparkles, Stethoscope } from "lucide-react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useAuth } from "../../context/AuthContext";
import api from "../../services/api";

const vitalsMap = { heart_rate:"Heart rate", blood_pressure:"Blood pressure", blood_glucose:"Blood glucose", spo2:"Oxygen saturation" };
const fmt = v => v ? new Date(v).toLocaleDateString("en-IN", {day:"numeric", month:"short", year:"numeric"}) : "—";

function PatientDashboard(){
 const {user}=useAuth();
 const [vitals,setVitals]=useState([]),[records,setRecords]=useState([]),[appointments,setAppointments]=useState([]),[prescriptions,setPrescriptions]=useState([]),[meds,setMeds]=useState([]),[loading,setLoading]=useState(true);
 const firstName=user?.name?.trim()?.split(" ")[0]||"there";
 useEffect(()=>{let live=true;(async()=>{const r=await Promise.allSettled([api.get("/vitals?limit=40"),api.get("/medical-records"),api.get("/appointments/my"),api.get("/prescriptions"),api.get("/prescriptions/medications/today")]);if(!live)return;setVitals(r[0].status==='fulfilled'?(r[0].value.data?.data||[]):[]);setRecords(r[1].status==='fulfilled'?(r[1].value.data?.data||[]):[]);setAppointments(r[2].status==='fulfilled'?(r[2].value.data?.data||[]):[]);setPrescriptions(r[3].status==='fulfilled'?(r[3].value.data?.data||[]):[]);setMeds(r[4].status==='fulfilled'?(r[4].value.data?.data||[]):[]);setLoading(false)})();return()=>{live=false}},[]);
 const latest={}; [...vitals].sort((a,b)=>new Date(b.recordedAt)-new Date(a.recordedAt)).forEach(v=>{if(!latest[v.type])latest[v.type]=v});
 const chart=[...vitals].filter(v=>v.type==='heart_rate').sort((a,b)=>new Date(a.recordedAt)-new Date(b.recordedAt)).slice(-7).map(v=>({day:new Date(v.recordedAt).toLocaleDateString('en-IN',{weekday:'short'}),value:Number(v.value)||0}));
 const upcoming=appointments.filter(a=>['pending','confirmed','approved'].includes(a.status)&&new Date(a.appointmentDate)>=new Date()).sort((a,b)=>new Date(a.appointmentDate)-new Date(b.appointmentDate)).slice(0,1);
 const activeMeds=meds.length || prescriptions.reduce((n,p)=>n+(p.medicines?.filter(m=>!m.endDate||new Date(m.endDate)>=new Date()).length||0),0);
 return <div className="patient-dashboard">
  <section className="patient-welcome"><div><div className="patient-page-eyebrow">PATIENT DASHBOARD</div><h1>Welcome, {firstName} <span>👋</span></h1><p>Here's a live overview of your health information and upcoming care.</p></div><div className="dashboard-date"><CalendarDays size={16}/><span>Today</span><strong>{fmt(new Date())}</strong></div></section>
  <section className="dashboard-section"><div className="dashboard-section-heading"><div><span>HEALTH OVERVIEW</span><h2>Your latest health signals</h2></div><button type="button" onClick={()=>window.location.href="/patient/health"}>View health monitor <ChevronRight size={16}/></button></div>
   <div className="vitals-grid"><VitalCard icon={<HeartPulse/>} label="Heart rate" data={latest.heart_rate} unit="BPM"/><VitalCard icon={<Activity/>} label="Blood pressure" data={latest.blood_pressure} unit="mmHg"/><VitalCard icon={<Activity/>} label="Blood glucose" data={latest.blood_glucose} unit="mg/dL"/><VitalCard icon={<Activity/>} label="Oxygen saturation" data={latest.spo2} unit="%"/></div>
  </section>
  <section className="dashboard-main-grid"><div className="dashboard-card health-trend-card"><div className="dashboard-card-heading"><div><span>HEART RATE TREND</span><h3>Recent activity</h3></div></div><div className="chart-area">{chart.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="value" stroke="#087f73" fill="#dff3ef" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<div className="dashboard-inline-empty">Add heart-rate readings in Health Monitor to see your real trend.</div>}</div></div>
   <div className="dashboard-card ai-dashboard-card"><div className="ai-card-top"><div className="ai-icon"><Sparkles size={19}/></div><span>MEDITRACK AI</span></div><h3>Personal health assistant</h3><p>Ask a health question, understand your symptoms and find the right doctor when needed.</p><button type="button" className="ai-action" onClick={()=>window.location.href="/patient/ai-insight"}>Open MediTrack AI <ArrowRight size={16}/></button></div></section>
  <section className="dashboard-bottom-grid"><DashboardCard section="APPOINTMENTS" title="Upcoming care" icon={<CalendarDays size={19}/>} message={upcoming.length?`Appointment with ${upcoming[0].doctor?.name||'doctor'}`:"No upcoming appointments"} description={upcoming.length?`${fmt(upcoming[0].appointmentDate)} · ${upcoming[0].appointmentTime||'Scheduled time'}`:"Book an appointment with a verified MediTrack doctor."} buttonText="Open appointments" onClick="/patient/appointments"/><DashboardCard section="MEDICATIONS" title="Today's medicines" icon={<Pill size={19}/>} message={activeMeds?`${activeMeds} medicine${activeMeds===1?'':'s'} active`:"No active medicines"} description={meds.length?"Your scheduled doses are shown in the medication center.":"Prescriptions and reminders will appear here after your doctor adds them."} buttonText="Open medicines" onClick="/patient/medicines"/><DashboardCard section="MEDICAL RECORDS" title="Recent documents" icon={<FileHeart size={19}/>} message={records.length?`${records.length} stored record${records.length===1?'':'s'}`:"No medical records yet"} description={records[0]?`${records[0].title} · ${fmt(records[0].documentDate||records[0].createdAt)}`:"Upload reports, scans and prescriptions securely."} buttonText="Open records" onClick="/patient/records"/></section>
  <section className="dashboard-card health-journey-card"><div className="dashboard-card-heading"><div><span>YOUR HEALTH JOURNEY</span><h3>Keep your care information connected</h3></div><HeartPulse size={20}/></div><div className="journey-items"><JourneyItem icon={<Stethoscope/>} title="Doctor consultations" text={`${appointments.length} appointment${appointments.length===1?'':'s'} stored`}/><JourneyItem icon={<FileHeart/>} title="Medical records" text={`${records.length} document${records.length===1?'':'s'} stored`}/><JourneyItem icon={<Pill/>} title="Medication history" text={`${prescriptions.length} prescription${prescriptions.length===1?'':'s'} stored`}/><JourneyItem icon={<Activity/>} title="Health progress" text={`${vitals.length} health reading${vitals.length===1?'':'s'} recorded`}/></div></section>
 </div>
}
function VitalCard({icon,label,data,unit}){let value='—',displayUnit=unit;if(data){value=data.type==='blood_pressure'?`${data.systolic}/${data.diastolic}`:data.value??'—';displayUnit=data.unit||unit}return <div className="vital-card"><div className="vital-icon">{icon}</div><div className="vital-title">{label}</div><div className="vital-value"><strong>{value}</strong><span>{displayUnit}</span></div><div className={`vital-status ${data?'ok':'neutral'}`}>{data?'Latest saved reading':'No recent reading'}</div></div>}
function DashboardCard({section,title,icon,message,description,buttonText,onClick}){return <div className="dashboard-card appointment-card"><div className="dashboard-card-heading"><div><span>{section}</span><h3>{title}</h3></div>{icon}</div><div className="empty-dashboard-state"><strong>{message}</strong><p>{description}</p><button type="button" onClick={()=>window.location.href=onClick}>{buttonText}<ArrowRight size={15}/></button></div></div>}
function JourneyItem({icon,title,text}){return <div className="journey-item"><div className="journey-icon">{icon}</div><div><strong>{title}</strong><p>{text}</p></div></div>}
export default PatientDashboard;
